version: '3'
services:
  web:
    build:
      context: ./web
      dockerfile: dev.Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - "./web:/usr/web:rw"
    links:
      - db
  db:
    image: mongo
    restart: always
